import {
  Activity,
  BadgeCheck,
  Brain,
  BriefcaseBusiness,
  ChefHat,
  CircleDollarSign,
  ClipboardCheck,
  GraduationCap,
  HeartPulse,
  Home,
  Music2,
  Scale,
  ShieldCheck,
  Store,
  Tractor,
  TrendingUp,
  Truck,
  UserRoundCheck,
  Utensils,
  Wrench,
} from 'lucide-react';

export const proofBadges = ['Real-Life Verified', 'AI Build Verified', 'Founder-Safe Verified'];

export const builders = [
  {
    id: 'sarah-malik',
    name: 'Dr. Sarah Malik',
    initials: 'SM',
    profession: 'Doctor',
    headline: 'With AI, I build clinical tools.',
    category: 'Health',
    industry: 'Healthcare / Clinic Operations',
    builds: ['Patient intake apps', 'Appointment triage', 'Clinic dashboards'],
    understands: ['Patient flow', 'Admin overload', 'Appointment delays', 'Clinical handoff'],
    tools: ['Cursor', 'Claude Code', 'Lovable', 'Supabase'],
    bestFor: 'Health-tech founders and clinic workflow MVPs',
    advantage: 'I know where clinic software breaks because I have lived it.',
    rating: 4.98,
    projects: 41,
    availability: 'Available in 2 weeks',
    price: '$4.8k+',
    location: 'Remote / Sydney',
    joined: 'Recently active',
    trending: true,
    booked: true,
    proofs: proofBadges,
    tags: ['Clinical ops', 'Triage', 'Patient flow'],
    profileBio:
      'Sarah helps founders turn clinical bottlenecks into working software. Her edge is knowing what happens between the appointment, the front desk, the nurse, and the doctor.',
    portfolio: ['ClinicFlow intake dashboard', 'TriageLite routing tool', 'Handoff Notes AI'],
    caseStudies: [
      'Reduced intake admin from 17 minutes to 6 minutes in a private clinic prototype.',
      'Built a triage workflow that helped founders validate a care navigation MVP in 21 days.',
    ],
    reviews: [
      'Sarah understood the clinic pressure before we explained the feature list.',
      'The first prototype felt like it was made by someone who had actually worked in a clinic.',
    ],
    pricing: ['Workflow audit: $900', 'Prototype sprint: $4,800', 'Clinic MVP: $12,000+'],
  },
  {
    id: 'tom-hargreaves',
    name: 'Tom Hargreaves',
    initials: 'TH',
    profession: 'Farmer',
    headline: 'With AI, I build ag-tech tools.',
    category: 'Agriculture',
    industry: 'Agriculture / Field Operations',
    builds: ['Farm task trackers', 'Crop dashboards', 'Equipment logs', 'Harvest planning tools'],
    understands: ['Weather pressure', 'Timing', 'Machinery breakdowns', 'Workers', 'Harvest chaos'],
    tools: ['Replit', 'Bolt', 'Airtable', 'Supabase'],
    bestFor: 'Ag-tech founders and rural business tools',
    advantage: 'I build for mud, weather, timing, and real farm chaos.',
    rating: 4.92,
    projects: 29,
    availability: 'Open this month',
    price: '$3.6k+',
    location: 'Remote / Regional',
    joined: 'Recently joined',
    trending: true,
    booked: false,
    proofs: proofBadges,
    tags: ['Field ops', 'Equipment', 'Harvest'],
  },
  {
    id: 'mahmood-khan',
    name: 'Mahmood Khan',
    initials: 'MK',
    profession: 'Music Producer / Artist / Label Operator',
    headline: 'With AI, I build creator tools.',
    category: 'Music',
    industry: 'Music / Creator Economy',
    builds: ['Catalog dashboards', 'Royalty workflows', 'DAW helper apps', 'Release planning tools'],
    understands: ['Stems', 'Sessions', 'Vocal chains', 'Metadata', 'Royalties', 'Creator blocks'],
    tools: ['Codex', 'Cursor', 'Claude', 'GitHub Pages', 'Supabase'],
    bestFor: 'Music-tech, creator-tech, plugins, artist workflows, and catalog products',
    advantage: 'I know what stops creators from finishing and releasing work.',
    rating: 4.97,
    projects: 37,
    availability: 'Taking 1 project',
    price: '$4.2k+',
    location: 'Remote / Melbourne',
    joined: 'Most booked',
    trending: true,
    booked: true,
    proofs: proofBadges,
    tags: ['Creator ops', 'Catalogs', 'Royalties'],
    profileBio:
      'Mahmood builds tools for the creative bottlenecks that do not show up in generic product specs: unfinished sessions, messy catalogs, missed metadata, and release pressure.',
    portfolio: ['SessionPilot release OS', 'RoyaltyDesk prototype', 'StemTag assistant'],
    caseStudies: [
      'Created a release dashboard for an indie label to track assets, metadata, masters, splits, and rollout tasks.',
      'Built a catalog admin prototype that turned scattered royalty notes into searchable project records.',
    ],
    reviews: [
      'A normal developer would have built a file manager. Mahmood built the workflow around finishing songs.',
      'He understood sessions, stems, splits, and creator blocks without a two-hour glossary.',
    ],
    pricing: ['Creator workflow map: $750', 'Prototype sprint: $4,200', 'Creator-tech MVP: $10,000+'],
  },
  {
    id: 'amira-haddad',
    name: 'Amira Haddad',
    initials: 'AH',
    profession: 'Restaurant Operator',
    headline: 'With AI, I build kitchen and ordering systems.',
    category: 'Food',
    industry: 'Food / Hospitality',
    builds: ['Preorder menus', 'Kitchen dashboards', 'Pickup systems', 'Stock and prep tools'],
    understands: ['Kitchen timing', 'Prep limits', 'Trust', 'Hygiene', 'Customer flow', 'Peak-hour pressure'],
    tools: ['Lovable', 'Bolt', 'Shopify', 'Airtable'],
    bestFor: 'Food-tech, home kitchen, takeaway, catering, and local ordering MVPs',
    advantage: 'I understand kitchen timing, trust, prep limits, and customer flow.',
    rating: 4.9,
    projects: 33,
    availability: 'Available now',
    price: '$3.8k+',
    location: 'Remote / Dubai',
    joined: 'Trending',
    trending: false,
    booked: true,
    proofs: proofBadges,
    tags: ['Ordering', 'Prep', 'Hospitality'],
  },
  {
    id: 'daniel-price',
    name: 'Daniel Price',
    initials: 'DP',
    profession: 'Trader',
    headline: 'With AI, I build trading dashboards.',
    category: 'Trading',
    industry: 'Trading / Market Systems',
    builds: ['Trading dashboards', 'Bot logs', 'Signal tools', 'Risk panels', 'Trade review systems'],
    understands: ['Pips', 'Spreads', 'Fake entries', 'MFE', 'Drawdown', 'Session timing', 'Broker limits'],
    tools: ['Cursor', 'Python', 'Replit', 'TradingView'],
    bestFor: 'Trading tools, backtest viewers, bot analytics, and risk systems',
    advantage: 'I know the difference between a chart that looks good and a tool that prevents bad trades.',
    rating: 4.91,
    projects: 26,
    availability: 'Booked until July',
    price: '$5.5k+',
    location: 'Remote / London',
    joined: 'Most booked',
    trending: true,
    booked: true,
    proofs: proofBadges,
    tags: ['Risk', 'Signals', 'Dashboards'],
  },
  {
    id: 'leah-nguyen',
    name: 'Leah Nguyen',
    initials: 'LN',
    profession: 'Nurse',
    headline: 'With AI, I build patient flow tools.',
    category: 'Health',
    industry: 'Nursing / Patient Flow',
    builds: ['Ward boards', 'Shift notes', 'Patient flow trackers'],
    understands: ['Shift handover', 'Capacity pressure', 'Discharge delays', 'Nurse communication'],
    tools: ['Claude', 'Airtable', 'Softr', 'Supabase'],
    bestFor: 'Care coordination, patient movement, and nursing workflow MVPs',
    advantage: 'I build for the moments where handover fails and everyone pays for it.',
    rating: 4.86,
    projects: 18,
    availability: 'Open next week',
    price: '$3.2k+',
    location: 'Remote / Brisbane',
    joined: 'Recently joined',
    trending: false,
    booked: false,
    proofs: proofBadges,
    tags: ['Handover', 'Ward ops', 'Care flow'],
  },
  {
    id: 'mateo-rivera',
    name: 'Mateo Rivera',
    initials: 'MR',
    profession: 'Teacher',
    headline: 'With AI, I build learning tools.',
    category: 'Education',
    industry: 'Education / Classroom Systems',
    builds: ['Lesson planners', 'Student feedback tools', 'Parent update systems'],
    understands: ['Classroom time', 'Assessment pressure', 'Student confidence', 'Parent communication'],
    tools: ['Bolt', 'Claude', 'Google Sheets', 'Firebase'],
    bestFor: 'Ed-tech founders, tutoring tools, and school workflow prototypes',
    advantage: 'I know when software helps teachers and when it just becomes another tab.',
    rating: 4.88,
    projects: 22,
    availability: 'Available now',
    price: '$2.9k+',
    location: 'Remote / Auckland',
    joined: 'Recently active',
    trending: false,
    booked: false,
    proofs: proofBadges,
    tags: ['Lessons', 'Assessment', 'Parents'],
  },
  {
    id: 'celine-rossi',
    name: 'Celine Rossi',
    initials: 'CR',
    profession: 'Chef',
    headline: 'With AI, I build kitchen systems.',
    category: 'Food',
    industry: 'Food / Kitchen Operations',
    builds: ['Prep planners', 'Recipe cost tools', 'Kitchen checklists'],
    understands: ['Margins', 'Prep windows', 'Stock waste', 'Kitchen handoff'],
    tools: ['Lovable', 'Airtable', 'Notion', 'Zapier'],
    bestFor: 'Kitchen ops, catering, menu systems, and food inventory MVPs',
    advantage: 'I build around the rush, not the demo.',
    rating: 4.84,
    projects: 20,
    availability: 'Open this month',
    price: '$3.1k+',
    location: 'Remote / Milan',
    joined: 'Trending',
    trending: true,
    booked: false,
    proofs: proofBadges,
    tags: ['Prep', 'Margins', 'Stock'],
  },
  {
    id: 'nora-finch',
    name: 'Nora Finch',
    initials: 'NF',
    profession: 'Paralegal',
    headline: 'With AI, I build legal intake tools.',
    category: 'Legal',
    industry: 'Legal / Intake Operations',
    builds: ['Qualified call engines', 'Matter intake forms', 'Case triage tools'],
    understands: ['Client urgency', 'Qualification', 'Conflict checks', 'Document chaos'],
    tools: ['Cursor', 'Claude', 'Typeform', 'Supabase'],
    bestFor: 'Legal-tech intake, call scoring, document routing, and CRM prototypes',
    advantage: 'I know the difference between a lead and a matter worth taking.',
    rating: 4.93,
    projects: 25,
    availability: 'Taking 2 projects',
    price: '$4.4k+',
    location: 'Remote / New York',
    joined: 'Most booked',
    trending: true,
    booked: true,
    proofs: proofBadges,
    tags: ['Intake', 'Case triage', 'Calls'],
  },
  {
    id: 'omar-brooks',
    name: 'Omar Brooks',
    initials: 'OB',
    profession: 'Mechanic',
    headline: 'With AI, I build workshop tools.',
    category: 'Field Service',
    industry: 'Automotive / Workshop Operations',
    builds: ['Job cards', 'Parts trackers', 'Inspection reports'],
    understands: ['Bay scheduling', 'Parts delays', 'Technician notes', 'Customer approvals'],
    tools: ['Replit', 'Airtable', 'Claude', 'Make'],
    bestFor: 'Workshop CRMs, mechanic apps, inspections, and service tracking MVPs',
    advantage: 'I build for the shop floor, not the boardroom diagram.',
    rating: 4.8,
    projects: 16,
    availability: 'Available now',
    price: '$2.7k+',
    location: 'Remote / Chicago',
    joined: 'Recently joined',
    trending: false,
    booked: false,
    proofs: proofBadges,
    tags: ['Workshops', 'Parts', 'Approvals'],
  },
  {
    id: 'ivy-chen',
    name: 'Ivy Chen',
    initials: 'IC',
    profession: 'Retailer',
    headline: 'With AI, I build inventory and ecommerce tools.',
    category: 'Retail',
    industry: 'Retail / Ecommerce Operations',
    builds: ['Inventory dashboards', 'Supplier trackers', 'Storefront workflows'],
    understands: ['Stockouts', 'Returns', 'Supplier gaps', 'Margin pressure'],
    tools: ['Shopify', 'Airtable', 'Zapier', 'Claude'],
    bestFor: 'Retail ops, ecommerce dashboards, stock tools, and boutique workflow MVPs',
    advantage: 'I know where inventory systems break during the busy week.',
    rating: 4.87,
    projects: 21,
    availability: 'Open next week',
    price: '$3.4k+',
    location: 'Remote / Singapore',
    joined: 'Trending',
    trending: false,
    booked: true,
    proofs: proofBadges,
    tags: ['Inventory', 'Ecommerce', 'Suppliers'],
  },
  {
    id: 'dr-maya-singh',
    name: 'Dr. Maya Singh',
    initials: 'MS',
    profession: 'Therapist',
    headline: 'With AI, I build mental health tools.',
    category: 'Mental Health',
    industry: 'Mental Health / Practice Systems',
    builds: ['Client journaling tools', 'Session prep apps', 'Practice dashboards'],
    understands: ['Trust', 'Privacy', 'Client safety', 'Session continuity'],
    tools: ['Claude', 'Cursor', 'Supabase', 'Notion'],
    bestFor: 'Mental health tools, practice workflows, journaling products, and care support MVPs',
    advantage: 'I build for trust before features.',
    rating: 4.95,
    projects: 19,
    availability: 'Taking 1 project',
    price: '$4.1k+',
    location: 'Remote / Toronto',
    joined: 'Recently active',
    trending: true,
    booked: false,
    proofs: proofBadges,
    tags: ['Trust', 'Journaling', 'Practice ops'],
  },
];

export const categories = [
  {
    name: 'Doctors building health tools',
    category: 'Health',
    icon: HeartPulse,
    count: 312,
    description: 'Clinical workflow, triage, patient intake, care coordination.',
  },
  {
    name: 'Teachers building education tools',
    category: 'Education',
    icon: GraduationCap,
    count: 214,
    description: 'Lessons, assessments, feedback loops, tutoring systems.',
  },
  {
    name: 'Farmers building agriculture tools',
    category: 'Agriculture',
    icon: Tractor,
    count: 148,
    description: 'Field operations, equipment logs, crop planning, harvest timing.',
  },
  {
    name: 'Musicians building creator tools',
    category: 'Music',
    icon: Music2,
    count: 186,
    description: 'Catalogs, royalties, DAW helpers, release workflows.',
  },
  {
    name: 'Chefs building kitchen systems',
    category: 'Food',
    icon: ChefHat,
    count: 132,
    description: 'Prep planning, stock, ordering, kitchen communication.',
  },
  {
    name: 'Legal teams building intake tools',
    category: 'Legal',
    icon: Scale,
    count: 121,
    description: 'Qualified intake, call scoring, document routing, CRM handoff.',
  },
  {
    name: 'Traders building market dashboards',
    category: 'Trading',
    icon: TrendingUp,
    count: 96,
    description: 'Risk panels, signal logs, trade review, backtest viewers.',
  },
  {
    name: 'Retailers building commerce tools',
    category: 'Retail',
    icon: Store,
    count: 178,
    description: 'Inventory, returns, suppliers, storefront operations.',
  },
  {
    name: 'Tradies building field-service tools',
    category: 'Field Service',
    icon: Wrench,
    count: 167,
    description: 'Jobs, dispatch, inspections, approvals, quoting.',
  },
  {
    name: 'Therapists building mental health tools',
    category: 'Mental Health',
    icon: Brain,
    count: 89,
    description: 'Practice systems, journaling, session continuity, safety.',
  },
  {
    name: 'Logistics operators building dispatch tools',
    category: 'Logistics',
    icon: Truck,
    count: 104,
    description: 'Routes, dispatch, driver notes, supply chain visibility.',
  },
  {
    name: 'Real estate agents building workflow tools',
    category: 'Real Estate',
    icon: Home,
    count: 93,
    description: 'Listings, inspections, buyer follow-up, vendor communication.',
  },
];

export const projects = [
  {
    name: 'ClinicFlow',
    domain: 'HealthTech',
    description: 'Patient intake and triage dashboard built by Dr. Sarah Malik.',
    builder: 'Dr. Sarah Malik',
    status: 'MVP Shipped',
    tools: ['Claude Code', 'Supabase', 'Cursor'],
  },
  {
    name: 'MudMap',
    domain: 'AgriTech',
    description: 'Farm task and equipment tracking built by Tom Hargreaves.',
    builder: 'Tom Hargreaves',
    status: 'Live',
    tools: ['Bolt', 'Airtable', 'Supabase'],
  },
  {
    name: 'SessionPilot',
    domain: 'CreatorTech',
    description: 'Music release workflow and catalog dashboard built by Mahmood Khan.',
    builder: 'Mahmood Khan',
    status: 'In Progress',
    tools: ['Codex', 'Claude', 'GitHub Pages'],
  },
  {
    name: 'KitchenDrop',
    domain: 'FoodTech',
    description: 'Preorder and pickup system for home kitchens built by Amira Haddad.',
    builder: 'Amira Haddad',
    status: 'MVP Shipped',
    tools: ['Lovable', 'Shopify', 'Airtable'],
  },
  {
    name: 'RiskLens',
    domain: 'TradingTech',
    description: 'Bot log dashboard and drawdown review system built by Daniel Price.',
    builder: 'Daniel Price',
    status: 'Live',
    tools: ['Python', 'Cursor', 'TradingView'],
  },
  {
    name: 'IntakeBridge',
    domain: 'LegalTech',
    description: 'Qualified legal intake and call scoring system built by Nora Finch.',
    builder: 'Nora Finch',
    status: 'MVP Shipped',
    tools: ['Claude', 'Supabase', 'Typeform'],
  },
];

export const testimonials = [
  {
    quote:
      'I did not have to explain the basics of my industry for two hours. She already knew where the workflow broke.',
    author: 'Founder, ClinicFlow',
  },
  {
    quote:
      'This felt completely different from hiring a freelancer. The builder understood the problem before we even talked about features.',
    author: 'Founder, KitchenDrop',
  },
  {
    quote:
      'A normal developer would have built the obvious app. My vibe coder helped me build the actual thing customers needed.',
    author: 'Founder, IntakeBridge',
  },
  {
    quote:
      'The prototype was lean, but it had the right instincts. That mattered more than a perfect architecture diagram.',
    author: 'Founder, RiskLens',
  },
];

export const comparisonRows = [
  ['Syntax-first', 'Experience-first'],
  ['Starts with code', 'Starts with the real problem'],
  ['Needs requirements', 'Works from lived pain'],
  ['Thinks in frameworks', 'Thinks in workflows'],
  ['Builds what is requested', 'Builds what is actually needed'],
  ['Uses AI to speed up coding', 'Uses AI to become a builder'],
  ['May over-engineer', 'Ships the simplest proof'],
  ['Asks "what stack?"', 'Asks "what pain?"'],
  ['Technical-first', 'Problem-first'],
  ['Knows how to build', 'Knows why it matters'],
];

export const comparisonCards = [
  ['Builds what the spec says', 'Builds what the problem needs'],
  ['Uses AI like autocomplete', 'Uses AI like a co-builder'],
  ['Can get stuck doing it perfectly', 'Ships the first useful version'],
  ['May build skyscrapers for lemonade stands', 'Builds lemonade stands that sell lemonade'],
  ['Sees technical constraints', 'Sees practical possibilities'],
  ['Knowledge-based builder', 'Experience-based builder'],
];

export const examples = [
  {
    title: 'Medical software',
    icon: Activity,
    coder: 'A coder builds a medical app. The coder builds what looks right.',
    vibe: 'A doctor who vibe codes builds a clinical tool that saves time, reduces errors, and matches reality.',
  },
  {
    title: 'Farming software',
    icon: Tractor,
    coder: 'A coder builds an agriculture dashboard about farming.',
    vibe: 'A farmer who vibe codes builds from inside farming: mud, rain, timing, breakdowns, and harvest chaos.',
  },
  {
    title: 'Music software',
    icon: Music2,
    coder: 'A coder builds a file manager with features.',
    vibe: 'A producer who vibe codes builds a workflow tool that helps artists actually finish songs.',
  },
  {
    title: 'Legal call platform',
    icon: Scale,
    coder: 'A coder builds a lead marketplace.',
    vibe: 'A legal-domain vibe coder builds a qualified-call engine around the actual value.',
  },
  {
    title: 'Home food platform',
    icon: Utensils,
    coder: 'A coder builds "Uber Eats for home kitchens."',
    vibe: 'A vibe coder builds a trust-first, compliance-first preorder system that matches how home kitchens operate.',
  },
  {
    title: 'Trading dashboard',
    icon: TrendingUp,
    coder: 'A coder builds charts that look analytical.',
    vibe: 'A trader who vibe codes builds decision support that helps prevent bad trades.',
  },
];

export const founderSteps = [
  ['Bring your idea', 'Start with the problem, the customer, and the pressure point.'],
  ['Find builders who understand your world', 'Search by real-life profession, domain, tools, and proof.'],
  ['Review experience-first cards', 'See what they build, what they understand, and where their edge comes from.'],
  ['Start a scoped build', 'Agree on a useful first version with clear ownership and milestones.'],
  ['Launch the first working version', 'Ship the proof, learn fast, and keep the keys.'],
];

export const builderSteps = [
  ['Show who you are in real life', 'Your profession becomes the first signal, not an afterthought.'],
  ['Prove the problem you understand', 'Explain the pain, workflow, stakes, and customers you know firsthand.'],
  ['Show what you can build with AI', 'Add demos, tools, build logs, and small proof projects.'],
  ['Get discovered by founders', 'Match with people building inside the world you already understand.'],
  ['Turn lived experience into software', 'Use AI to make useful tools real faster than the old path allowed.'],
];

export const trustFeatures = [
  {
    icon: UserRoundCheck,
    title: 'Experience-First Matching',
    text: 'Find builders who understand your world before they touch the code.',
  },
  {
    icon: BadgeCheck,
    title: 'Real-Life Verified',
    text: 'Builders prove the profession, workflow, or problem they know.',
  },
  {
    icon: ShieldCheck,
    title: 'AI Build Verified',
    text: 'See live demos, prototypes, tools used, and AI-built work.',
  },
  {
    icon: ClipboardCheck,
    title: 'Founder-Safe Verified',
    text: 'Milestones, repo access, communication, and handover are part of the trust layer.',
  },
  {
    icon: BriefcaseBusiness,
    title: 'Project Rooms',
    text: 'Chat, scope, share files, review build logs, and keep the MVP organized.',
  },
  {
    icon: CircleDollarSign,
    title: 'Milestone-Based Builds',
    text: 'No black box work. Clear scope, visible progress, clean handover.',
  },
];

export const vibeCoderSignals = [
  ['You do not know how to code traditionally, and that is not a weakness.', 'You are not trapped by framework-first thinking. You build from intuition, experience, and the problem.'],
  ['You learned to build by talking to AI, not memorizing syntax.', 'You describe what you want, iterate, refine, test, and ship.'],
  ['You do not get stuck in proper engineering paralysis.', 'You care about whether it works, solves the problem, and can become a useful first version.'],
  ['You do not over-engineer.', 'You build the simplest version that proves the idea.'],
  ['You do not obsess over frameworks.', 'You care less about React vs Vue and more about making the thing real.'],
  ['You can start with only an idea.', 'You do not begin with "Is this possible?" You begin with "Let us try it."'],
  ['You understand a real-world problem deeply.', 'You have lived the workflow, pain, bottleneck, pressure, customer, timing, and stakes firsthand.'],
  ['You use AI as a building partner.', 'AI is not just autocomplete. It is your co-builder.'],
  ['You care more about solving the problem than sounding technical.', 'You are not trying to impress engineers. You are trying to make something useful exist.'],
  ['You build from life.', 'Your real-world experience is the source code.'],
];
